# Generated by Django 4.1 on 2022-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=256)),
                ('stars', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
    ]
